/* Generated by Together */

#include "FinishPoint.hpp"

bool 
FinishPoint::transition_enter(const AIRCRAFT_STATE & ref_now, 
                                   const AIRCRAFT_STATE & ref_last)
{
  bool entered = ObservationZone::transition_enter(ref_now, ref_last);
  if (entered && (state_entered.Time<0)) {
    state_entered = ref_now;
    // only save first enter of finish
  }
  return entered;
}

double
FinishPoint::getElevation()
{
  // TODO: adjustments in FAI finish for min finish height
  return Elevation; // + SAFETYARRIVALHEIGHT
}
