/* Generated by Together */

#ifndef INTERMEDIATEPOINT_H
#define INTERMEDIATEPOINT_H
#include "OrderedTaskPoint.hpp"

class IntermediatePoint: 
  public OrderedTaskPoint {
public:    
  IntermediatePoint(const WAYPOINT & wp): 
    OrderedTaskPoint(wp) 
    {};


    
};
#endif //INTERMEDIATEPOINT_H
