/* Generated by Together */

#ifndef INTERMEDIATEPOINT_H
#define INTERMEDIATEPOINT_H
#include "OrderedTaskPoint.hpp"

class IntermediatePoint: 
  public OrderedTaskPoint {
public:    
  IntermediatePoint(const WAYPOINT & wp, bool b_scored): 
    OrderedTaskPoint(wp, b_scored) 
    {};
  virtual double getElevation();
};
#endif //INTERMEDIATEPOINT_H
