/* Generated by Together */

#include "StartPoint.hpp"

bool 
StartPoint::transition_exit(const AIRCRAFT_STATE & ref_now, 
                                  const AIRCRAFT_STATE & ref_last)
{
  // consider entry of start zone to be same as exit point

  bool exited = OrderedTaskPoint::transition_exit(ref_now, ref_last);
  if (exited) {
    state_entered = ref_last;
  }
  return exited;
}
