/* Generated by Together */
class OrderedTaskPoint;
struct GEOPOINT;

#ifndef TASKLEG_H
#define TASKLEG_H

class TaskLeg {
public:

  TaskLeg(OrderedTaskPoint& origin,
    OrderedTaskPoint& destination);

    OrderedTaskPoint * get_origin() const;

    OrderedTaskPoint * get_destination() const;

    double leg_distance_nominal();

    double leg_distance_scored(const GEOPOINT &ref);

    double leg_distance_travelled(const GEOPOINT &ref);

    double leg_distance_remaining(const GEOPOINT &ref);

    void update_geometry();

private:    
    OrderedTaskPoint * const tp_destination;
    OrderedTaskPoint * const tp_origin;
};
#endif //TASKLEG_H
