/* Generated by Together */

#include "FAICylinderASTPoint.hpp"

double FAICylinderASTPoint::score_adjustment() {
  return oz.score_adjustment();
}

GEOPOINT FAICylinderASTPoint::get_boundary_parametric(double t) 
{ 
  return oz.get_boundary_parametric(t);
}

