/* Generated by Together */

#include "FAISectorASTPoint.hpp"

double FAISectorASTPoint::score_adjustment()
{
  return 0.0;
}

GEOPOINT FAISectorASTPoint::get_boundary_parametric(double t) 
{ 
  return oz.get_boundary_parametric(t);
}
