set(_SOURCES
        Look/AircraftLook.cpp
        Look/AirspaceLook.cpp
        Look/AutoFont.cpp
        Look/ButtonLook.cpp
        Look/ChartLook.cpp
        Look/CheckBoxLook.cpp
        Look/ClimbPercentLook.cpp
        Look/CrossSectionLook.cpp
        Look/DefaultFonts.cpp
        Look/DialogLook.cpp
        Look/FinalGlideBarLook.cpp
        Look/FlarmTrafficLook.cpp
        Look/FontDescription.cpp
        Look/GestureLook.cpp
        Look/GlobalFonts.cpp
        Look/HorizonLook.cpp
        Look/IconLook.cpp
        Look/InfoBoxLook.cpp
        Look/Look.cpp
        Look/MapLook.cpp
        Look/NOAALook.cpp
        Look/OverlayLook.cpp
        Look/TaskLook.cpp
        Look/TerminalLook.cpp
        Look/ThermalAssistantLook.cpp
        Look/ThermalBandLook.cpp
        Look/TopographyLook.cpp
        Look/TraceHistoryLook.cpp
        Look/TrafficLook.cpp
        Look/TrailLook.cpp
        Look/VarioBarLook.cpp
        Look/VarioLook.cpp
        Look/WaveLook.cpp
        Look/WaypointLook.cpp
        Look/WindArrowLook.cpp
)

set(SCRIPT_FILES
    CMakeSource.cmake
)
