// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

#include "CountryName.hpp"
#include "Language/Language.hpp"
#include "util/CharUtil.hxx"
#include "util/StringAPI.hxx"

#include <algorithm>
#include <iterator>
#include <string_view>

struct CountryName {
  const char *code;
  const char *name;
};

static constexpr CountryName country_names[] = {
  { "AD", N_("Andorra") },
  { "AE", N_("United Arab Emirates") },
  { "AF", N_("Afghanistan") },
  { "AG", N_("Antigua and Barbuda") },
  { "AI", N_("Anguilla") },
  { "AL", N_("Albania") },
  { "AM", N_("Armenia") },
  { "AO", N_("Angola") },
  { "AQ", N_("Antarctica") },
  { "AR", N_("Argentina") },
  { "AS", N_("American Samoa") },
  { "AT", N_("Austria") },
  { "AU", N_("Australia") },
  { "AW", N_("Aruba") },
  { "AX", N_("Åland Islands") },
  { "AZ", N_("Azerbaijan") },
  { "BA", N_("Bosnia and Herzegovina") },
  { "BB", N_("Barbados") },
  { "BD", N_("Bangladesh") },
  { "BE", N_("Belgium") },
  { "BF", N_("Burkina Faso") },
  { "BG", N_("Bulgaria") },
  { "BH", N_("Bahrain") },
  { "BI", N_("Burundi") },
  { "BJ", N_("Benin") },
  { "BL", N_("Saint Barthélemy") },
  { "BM", N_("Bermuda") },
  { "BN", N_("Brunei") },
  { "BO", N_("Bolivia") },
  { "BQ", N_("Caribbean Netherlands") },
  { "BR", N_("Brazil") },
  { "BS", N_("Bahamas") },
  { "BT", N_("Bhutan") },
  { "BV", N_("Bouvet Island") },
  { "BW", N_("Botswana") },
  { "BY", N_("Belarus") },
  { "BZ", N_("Belize") },
  { "CA", N_("Canada") },
  { "CC", N_("Cocos Islands") },
  { "CD", N_("Congo-Kinshasa") },
  { "CF", N_("Central African Republic") },
  { "CG", N_("Congo-Brazzaville") },
  { "CH", N_("Switzerland") },
  { "CI", N_("Côte d'Ivoire") },
  { "CK", N_("Cook Islands") },
  { "CL", N_("Chile") },
  { "CM", N_("Cameroon") },
  { "CN", N_("China") },
  { "CO", N_("Colombia") },
  { "CR", N_("Costa Rica") },
  { "CU", N_("Cuba") },
  { "CV", N_("Cape Verde") },
  { "CW", N_("Curaçao") },
  { "CX", N_("Christmas Island") },
  { "CY", N_("Cyprus") },
  { "CZ", N_("Czechia") },
  { "DE", N_("Germany") },
  { "DJ", N_("Djibouti") },
  { "DK", N_("Denmark") },
  { "DM", N_("Dominica") },
  { "DO", N_("Dominican Republic") },
  { "DZ", N_("Algeria") },
  { "EC", N_("Ecuador") },
  { "EE", N_("Estonia") },
  { "EG", N_("Egypt") },
  { "EH", N_("Western Sahara") },
  { "ER", N_("Eritrea") },
  { "ES", N_("Spain") },
  { "ET", N_("Ethiopia") },
  { "FI", N_("Finland") },
  { "FJ", N_("Fiji") },
  { "FK", N_("Falkland Islands") },
  { "FM", N_("Micronesia") },
  { "FO", N_("Faroe Islands") },
  { "FR", N_("France") },
  { "GA", N_("Gabon") },
  { "GB", N_("United Kingdom") },
  { "GD", N_("Grenada") },
  { "GE", N_("Georgia") },
  { "GF", N_("French Guiana") },
  { "GG", N_("Guernsey") },
  { "GH", N_("Ghana") },
  { "GI", N_("Gibraltar") },
  { "GL", N_("Greenland") },
  { "GM", N_("Gambia") },
  { "GN", N_("Guinea") },
  { "GP", N_("Guadeloupe") },
  { "GQ", N_("Equatorial Guinea") },
  { "GR", N_("Greece") },
  { "GS", N_("South Georgia") },
  { "GT", N_("Guatemala") },
  { "GU", N_("Guam") },
  { "GW", N_("Guinea-Bissau") },
  { "GY", N_("Guyana") },
  { "HK", N_("Hong Kong") },
  { "HM", N_("Heard Island") },
  { "HN", N_("Honduras") },
  { "HR", N_("Croatia") },
  { "HT", N_("Haiti") },
  { "HU", N_("Hungary") },
  { "ID", N_("Indonesia") },
  { "IE", N_("Ireland") },
  { "IL", N_("Israel") },
  { "IM", N_("Isle of Man") },
  { "IN", N_("India") },
  { "IO", N_("British Indian Ocean Territory") },
  { "IQ", N_("Iraq") },
  { "IR", N_("Iran") },
  { "IS", N_("Iceland") },
  { "IT", N_("Italy") },
  { "JE", N_("Jersey") },
  { "JM", N_("Jamaica") },
  { "JO", N_("Jordan") },
  { "JP", N_("Japan") },
  { "KE", N_("Kenya") },
  { "KG", N_("Kyrgyzstan") },
  { "KH", N_("Cambodia") },
  { "KI", N_("Kiribati") },
  { "KM", N_("Comoros") },
  { "KN", N_("Saint Kitts and Nevis") },
  { "KP", N_("North Korea") },
  { "KR", N_("South Korea") },
  { "KW", N_("Kuwait") },
  { "KY", N_("Cayman Islands") },
  { "KZ", N_("Kazakhstan") },
  { "LA", N_("Laos") },
  { "LB", N_("Lebanon") },
  { "LC", N_("Saint Lucia") },
  { "LI", N_("Liechtenstein") },
  { "LK", N_("Sri Lanka") },
  { "LR", N_("Liberia") },
  { "LS", N_("Lesotho") },
  { "LT", N_("Lithuania") },
  { "LU", N_("Luxembourg") },
  { "LV", N_("Latvia") },
  { "LY", N_("Libya") },
  { "MA", N_("Morocco") },
  { "MC", N_("Monaco") },
  { "MD", N_("Moldova") },
  { "ME", N_("Montenegro") },
  { "MF", N_("Saint Martin") },
  { "MG", N_("Madagascar") },
  { "MH", N_("Marshall Islands") },
  { "MK", N_("North Macedonia") },
  { "ML", N_("Mali") },
  { "MM", N_("Myanmar") },
  { "MN", N_("Mongolia") },
  { "MO", N_("Macao") },
  { "MP", N_("Northern Mariana Islands") },
  { "MQ", N_("Martinique") },
  { "MR", N_("Mauritania") },
  { "MS", N_("Montserrat") },
  { "MT", N_("Malta") },
  { "MU", N_("Mauritius") },
  { "MV", N_("Maldives") },
  { "MW", N_("Malawi") },
  { "MX", N_("Mexico") },
  { "MY", N_("Malaysia") },
  { "MZ", N_("Mozambique") },
  { "NA", N_("Namibia") },
  { "NC", N_("New Caledonia") },
  { "NE", N_("Niger") },
  { "NF", N_("Norfolk Island") },
  { "NG", N_("Nigeria") },
  { "NI", N_("Nicaragua") },
  { "NL", N_("Netherlands") },
  { "NO", N_("Norway") },
  { "NP", N_("Nepal") },
  { "NR", N_("Nauru") },
  { "NU", N_("Niue") },
  { "NZ", N_("New Zealand") },
  { "OM", N_("Oman") },
  { "PA", N_("Panama") },
  { "PE", N_("Peru") },
  { "PF", N_("French Polynesia") },
  { "PG", N_("Papua New Guinea") },
  { "PH", N_("Philippines") },
  { "PK", N_("Pakistan") },
  { "PL", N_("Poland") },
  { "PM", N_("Saint Pierre and Miquelon") },
  { "PN", N_("Pitcairn") },
  { "PR", N_("Puerto Rico") },
  { "PS", N_("Palestine") },
  { "PT", N_("Portugal") },
  { "PW", N_("Palau") },
  { "PY", N_("Paraguay") },
  { "QA", N_("Qatar") },
  { "RE", N_("Réunion") },
  { "RO", N_("Romania") },
  { "RS", N_("Serbia") },
  { "RU", N_("Russia") },
  { "RW", N_("Rwanda") },
  { "SA", N_("Saudi Arabia") },
  { "SB", N_("Solomon Islands") },
  { "SC", N_("Seychelles") },
  { "SD", N_("Sudan") },
  { "SE", N_("Sweden") },
  { "SG", N_("Singapore") },
  { "SH", N_("Saint Helena") },
  { "SI", N_("Slovenia") },
  { "SJ", N_("Svalbard and Jan Mayen") },
  { "SK", N_("Slovakia") },
  { "SL", N_("Sierra Leone") },
  { "SM", N_("San Marino") },
  { "SN", N_("Senegal") },
  { "SO", N_("Somalia") },
  { "SR", N_("Suriname") },
  { "SS", N_("South Sudan") },
  { "ST", N_("São Tomé and Príncipe") },
  { "SV", N_("El Salvador") },
  { "SX", N_("Sint Maarten") },
  { "SY", N_("Syria") },
  { "SZ", N_("Eswatini") },
  { "TC", N_("Turks and Caicos Islands") },
  { "TD", N_("Chad") },
  { "TF", N_("French Southern Territories") },
  { "TG", N_("Togo") },
  { "TH", N_("Thailand") },
  { "TJ", N_("Tajikistan") },
  { "TK", N_("Tokelau") },
  { "TL", N_("Timor-Leste") },
  { "TM", N_("Turkmenistan") },
  { "TN", N_("Tunisia") },
  { "TO", N_("Tonga") },
  { "TR", N_("Turkey") },
  { "TT", N_("Trinidad and Tobago") },
  { "TV", N_("Tuvalu") },
  { "TW", N_("Taiwan") },
  { "TZ", N_("Tanzania") },
  { "UA", N_("Ukraine") },
  { "UG", N_("Uganda") },
  { "UM", N_("U.S. Outlying Islands") },
  { "US", N_("United States") },
  { "UY", N_("Uruguay") },
  { "UZ", N_("Uzbekistan") },
  { "VA", N_("Vatican City") },
  { "VC", N_("Saint Vincent and the Grenadines") },
  { "VE", N_("Venezuela") },
  { "VG", N_("British Virgin Islands") },
  { "VI", N_("U.S. Virgin Islands") },
  { "VN", N_("Vietnam") },
  { "VU", N_("Vanuatu") },
  { "WF", N_("Wallis and Futuna") },
  { "WS", N_("Samoa") },
  { "XK", N_("Kosovo") },
  { "YE", N_("Yemen") },
  { "YT", N_("Mayotte") },
  { "ZA", N_("South Africa") },
  { "ZM", N_("Zambia") },
  { "ZW", N_("Zimbabwe") },
};

static constexpr bool
CountryNamesAreSorted() noexcept
{
  for (std::size_t i = 1; i < std::size(country_names); ++i)
    if (std::string_view{country_names[i].code} <=
        std::string_view{country_names[i - 1].code})
      return false;
  return true;
}

static_assert(CountryNamesAreSorted());

const char *
GetCountryName(std::string_view area) noexcept
{
  if (area.size() != 2)
    return nullptr;

  const char code[3] = {
    ToUpperASCII(area[0]),
    ToUpperASCII(area[1]),
    '\0',
  };

  const auto *end = std::end(country_names);
  const auto *i = std::lower_bound(std::begin(country_names), end,
                                   code,
                                   [](const CountryName &item,
                                      const char *c) {
                                     return StringCompare(item.code, c) < 0;
                                   });
  if (i != end && StringIsEqual(i->code, code))
    return i->name;

  return nullptr;
}
