/* Generated by Together */

#ifndef INTERMEDIATEPOINT_H
#define INTERMEDIATEPOINT_H
#include "OrderedTaskPoint.hpp"

class IntermediatePoint: 
  public OrderedTaskPoint {
public:    
  IntermediatePoint(const TaskProjection& tp,
                    const WAYPOINT & wp, 
                    const bool b_scored): 
    OrderedTaskPoint(tp, wp, b_scored) 
    {};
  virtual double getElevation();
};
#endif //INTERMEDIATEPOINT_H
