/* Generated by Together */

#ifndef TASKLEG_H
#define TASKLEG_H

class OrderedTaskPoint;
struct GEOPOINT;

class TaskLeg {
protected:

  double leg_distance_nominal(const OrderedTaskPoint *origin,
                              const OrderedTaskPoint *destination) const;

  double leg_distance_planned(const OrderedTaskPoint *origin,
                              const OrderedTaskPoint *destination) const;
  
  double leg_distance_scored(const OrderedTaskPoint *origin,
                             const OrderedTaskPoint *destination,
                             const GEOPOINT &ref) const;
  
  double leg_distance_travelled(const OrderedTaskPoint *origin,
                                const OrderedTaskPoint *destination,
                                const GEOPOINT &ref) const;
  
  double leg_distance_remaining(const OrderedTaskPoint *origin,
                                const OrderedTaskPoint *destination,
                                const GEOPOINT &ref) const;
  
  double leg_distance_max(const OrderedTaskPoint *origin,
                          const OrderedTaskPoint *destination) const;
  
  double leg_distance_min(const OrderedTaskPoint *origin,
                          const OrderedTaskPoint *destination) const;
  
  double leg_bearing_travelled(const OrderedTaskPoint *origin,
                               const OrderedTaskPoint *destination,
                               const GEOPOINT &ref) const;
  
  double leg_bearing_remaining(const OrderedTaskPoint *origin,
                               const OrderedTaskPoint *destination,
                               const GEOPOINT &ref) const;
  
  double leg_bearing_planned(const OrderedTaskPoint *origin,
                             const OrderedTaskPoint *destination) const;

};
#endif //TASKLEG_H
