/* Generated by Together */

#include "CylinderZone.hpp"
#include <math.h>
#include "Util.h"

double CylinderZone::score_adjustment()
{
  return Radius;
}

GEOPOINT CylinderZone::get_boundary_parametric(double t) 
{ 
  return ::FindLocation(getLocation(),t*360,Radius);
}
