/* Generated by Together */

#ifndef HEIGHTLIMITZONE_H
#define HEIGHTLIMITZONE_H
class HeightLimitZone {
    
public:

    bool isInLimit();

protected:
    double maxHeight;
    double minHeight;
protected:
};
#endif //HEIGHTLIMITZONE_H