// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

#pragma once

#include <chrono>
#include <optional>
#include <span>
#include <string_view>

/**
 * One entry of XCSoar's time zone table.
 */
struct TimeZoneEntry {
  /** the IANA id, e.g. "Europe/Berlin" */
  const char *id;

  /** the POSIX TZ string, e.g. "CET-1CEST,M3.5.0,M10.5.0/3" */
  const char *posix;
};

/**
 * Returns the table of time zones known to XCSoar, sorted by id.  It is
 * generated by tools/GenerateTimeZones.py from the zoneinfo database.
 */
[[gnu::const]]
std::span<const TimeZoneEntry> GetTimeZones() noexcept;

/**
 * Look up a time zone by its IANA id.
 *
 * @return nullptr if there is no such time zone in our table
 */
[[gnu::pure]]
const TimeZoneEntry *FindTimeZone(std::string_view id) noexcept;

/**
 * Determine the UTC offset (seconds east of UTC) of the given time zone
 * at the given point in time, including daylight saving time.
 *
 * @return std::nullopt if there is no such time zone in our table
 */
[[gnu::pure]]
std::optional<std::chrono::seconds>
FindTimeZoneOffset(std::string_view id,
                   std::chrono::system_clock::time_point t) noexcept;
