Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"

    config.vm.synced_folder "../..", "/xcsoar-host-src"

    # Change directory to shared folder directory when connecting using vagrant ssh
    config.ssh.extra_args = ["-t", "cd /xcsoar-host-src; bash --login"]

    config.vm.define "XCSoarDevEnv"
    config.vm.hostname = "XCSoarDevEnv"

    config.vm.provider "virtualbox" do |v|
        host = RbConfig::CONFIG['host_os']

        v.name = "xcsoar-" + Time.now.strftime("%y%m%d%H%M")

        # Give VM 1/2 system memory & access to all cpu cores on the host
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 2

        elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 2

        else
            cpus = 4
            mem = 2048
        end

        v.customize ["modifyvm", :id, "--memory", mem]
        v.customize ["modifyvm", :id, "--cpus", cpus]

        # Decrease VirtualBox timesync threshold to 500 ms
        v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 500]
    end

    config.vm.provision "os_setup", type: "shell", privileged: false, inline: <<-SCRIPT
        set -e
        
        if ! grep -q "export LANG=C" ~/.profile ; then
            echo "export LANG=C" >> ~/.profile
        fi
        if ! grep -q "export LC_CTYPE=C" ~/.profile ; then
            echo "export LC_CTYPE=C" >> ~/.profile
        fi

        sudo apt-get update
    SCRIPT

    config.vm.provision "install-debian-packages", type: "shell", path: "../provisioning/install-debian-packages.sh"

    config.vm.provision "install-android-tools", type: "shell", privileged: false, path: "../provisioning/install-android-tools.sh"

    config.vm.provision "xcsoar_source", type: "shell", privileged: false, inline: <<-SCRIPT
        sudo apt-get clean

        cd
        git clone --recurse-submodules -o host /xcsoar-host-src xcsoar-src
        cd xcsoar-src
        git remote add master https://github.com/XCSoar/XCSoar.git

        make TARGET=UNIX
    SCRIPT
end
