set(_SOURCES
        Geo/Boost/RangeBox.cpp
        Geo/ConvexHull/GrahamScan.cpp
        Geo/ConvexHull/PolygonInterior.cpp
        Geo/Flat/FlatBoundingBox.cpp
        Geo/Flat/FlatEllipse.cpp
        Geo/Flat/FlatGeoPoint.cpp
        Geo/Flat/FlatLine.cpp
        Geo/Flat/FlatPoint.cpp
        Geo/Flat/FlatProjection.cpp
        Geo/Flat/FlatRay.cpp
        Geo/Flat/TaskProjection.cpp
        Geo/GeoBounds.cpp
        Geo/GeoClip.cpp
        Geo/GeoEllipse.cpp
        Geo/Geoid.cpp
        Geo/GeoPoint.cpp
        Geo/GeoVector.cpp
        Geo/Math.cpp # aug: von mir umgenannt
        Geo/Memento/DistanceMemento.cpp
        Geo/Memento/GeoVectorMemento.cpp
        Geo/Quadrilateral.cpp
        Geo/SearchPoint.cpp
        Geo/SearchPointVector.cpp
        Geo/SimplifiedMath.cpp
        Geo/UTM.cpp
)

set(SCRIPT_FILES
    CMakeSource.cmake
)
