name 'maestrodev-android'
version '1.0.1'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-android'
source 'http://github.com/maestrodev/puppet-android'
summary 'Android SDK module for Puppet'
description 'A Puppet module to install the Android SDK.'
dependency 'maestrodev/wget', '>=0.0.1'
