/* Generated by Together */

#include "AATPoint.hpp"
#include "Math/Geometry.hpp"
#include <math.h>

const GEOPOINT&
AATPoint::get_location_remaining() const
{
  if (getActiveState() == BEFORE_ACTIVE) {
    return get_location_max();
  } else {
    return m_target_location;
  }
}

bool 
AATPoint::update_sample(const AIRCRAFT_STATE& state,
                        const TaskEvents &task_events) 
{
  bool retval = OrderedTaskPoint::update_sample(state,task_events);
  if (getActiveState() == CURRENT_ACTIVE) {
    retval |= check_target(state);
  }

  return retval;
}

bool
AATPoint::check_target(const AIRCRAFT_STATE& state) 
{
  bool moved = false;
  if (isInSector(state)) {
    moved = check_target_inside(state);
  } else {
    moved = check_target_outside(state);
  }

  return moved;
}

bool 
AATPoint::close_to_target(const AIRCRAFT_STATE& state, const double threshold) const
{
  return (double_leg_distance(m_target_location)-double_leg_distance(state.Location)
          <= threshold);
}

bool
AATPoint::check_target_inside(const AIRCRAFT_STATE& state) 
{
  // target must be moved if d(p_last,t)+d(t,p_next) 
  //    < d(p_last,state)+d(state,p_next)

  if (close_to_target(state)) {
    const double d_to_max = state.Location.distance(get_location_max());
    if (d_to_max<=0.0) {
      // no improvement available
      return false;
    } else {
      m_target_location = state.Location;
      return true;
    }
  } else {
    return false;
  }
}

bool
AATPoint::check_target_outside(const AIRCRAFT_STATE& state) 
{
  return false;
/*
  // this is optional, to be replaced!
  
  // now uses TaskOptTarget

  if (!get_previous()->isInSector(state)) {
    double b0s = get_previous()->get_location_remaining()
      .bearing(state.Location);
    GeoVector vst(state.Location,m_target_location);
    double da = ::AngleLimit180(b0s-vst.Bearing);
    if ((fabs(da)>2.0) && (vst.Distance>1.0)) {
      AATIsolineIntercept ai(*this);
      AIRCRAFT_STATE si;
      if (ai.intercept(*this, state, 0.0, si.Location)
          && isInSector(si)) {

        // Note that this fights with auto-target

        m_target_location = si.Location;

        return true;
      }
    }
  }
  return false;
*/
}


bool
AATPoint::set_range(const double p, const bool force_if_current)
{
  switch (getActiveState()) {
  case CURRENT_ACTIVE:
    if (!has_entered() || force_if_current) {
      m_target_location = get_location_min().interpolate(get_location_max(),p);
      return true;
    }
    return false;
  case AFTER_ACTIVE:
    if (getActiveState() == AFTER_ACTIVE) {
      m_target_location = get_location_min().interpolate(get_location_max(),p);
      return true;
    }
  default:
    return false;
  }
  return false;
}


void 
AATPoint::set_target(const GEOPOINT &loc)
{
  m_target_location = loc;
}


bool
AATPoint::equals(const OrderedTaskPoint* other) const
{
  if (dynamic_cast<const AATPoint*>(other)) {
    return OrderedTaskPoint::equals(other);
  } else {
    return false;
  }
}
