/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT BY HAND - see Common/Data/Status/xcs2cpp.pl */

_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("DEFAULT");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_WAV_DRIP");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Pan mode ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Pan mode OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("AutoZoom ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("AutoZoom OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Calibrate ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Calibrate OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Simulation\r\nNothing is real!");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Maintain effective\r\nLOOKOUT at all times");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Closest Airfield Changed!");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("SnailTrail OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("SnailTrail ON Long");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("SnailTrail ON Short");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Vario Sounds ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Vario Sounds OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Dropped marker");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_WAV_BEEPBWEEP");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Waiting for GPS Connection");
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Restarting Comm Ports");
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Waiting for GPS Fix");
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("XCI Error");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_FAIL");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 30000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("McCready Value");
StatusMessageData[StatusMessageData_Size].delay_ms = 5000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Auto McCready ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Auto McCready OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Task Aborted");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Task Resume");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Bugs Performance");
StatusMessageData[StatusMessageData_Size].delay_ms = 5000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Ballast %");
StatusMessageData[StatusMessageData_Size].delay_ms = 5000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Logger ON");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Logger OFF");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_REMOVE");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Airspace Query");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_FAIL");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 7000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Toppology / Terrain");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_INSERT");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 2500;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Status");
StatusMessageData[StatusMessageData_Size].delay_ms = 60000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Organiser Battery Low");
StatusMessageData[StatusMessageData_Size].sound = TEXT("IDR_FAIL");
StatusMessageData[StatusMessageData_Size].doSound = true;
StatusMessageData[StatusMessageData_Size].delay_ms = 10000;
StatusMessageData_Size++;
_init_Status(StatusMessageData_Size);
StatusMessageData[StatusMessageData_Size].key = TEXT("Dummy");
StatusMessageData[StatusMessageData_Size].delay_ms = 1500;
StatusMessageData_Size++;
