/* AUTOMATICALLY GENERATED FILE - DO NOT EDIT BY HAND - see Common/Data/Status/xcs2cpp.pl */

_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("DEFAULT");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_WAV_DRIP");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Pan mode ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Pan mode OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("AutoZoom ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("AutoZoom OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Calibrate ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Calibrate OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Simulation\r\nNothing is real!");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Maintain effective\r\nLOOKOUT at all times");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Closest Airfield Changed!");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("SnailTrail OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("SnailTrail ON Long");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("SnailTrail ON Short");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Vario Sounds ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Vario Sounds OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Dropped marker");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_WAV_BEEPBWEEP");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Waiting for GPS Connection");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Restarting Comm Ports");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Waiting for GPS Fix");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("XCI Error");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_FAIL");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 30000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("McCready Value");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 5000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Auto McCready ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Auto McCready OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Task Aborted");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Task Resume");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Bugs Performance");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 5000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Ballast %");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 5000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Logger ON");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Logger OFF");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_REMOVE");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Airspace Warning");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_FAIL");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 7000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Toppology / Terrain");
StatusMessageCache[StatusMessageCache_Size].sound = TEXT("IDR_INSERT");
StatusMessageCache[StatusMessageCache_Size].doSound = true;
StatusMessageCache[StatusMessageCache_Size].delay_ms = 2500;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Status");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 60000;
StatusMessageCache_Size++;
_init_Status(StatusMessageCache_Size);
StatusMessageCache[StatusMessageCache_Size].key = TEXT("Dummy");
StatusMessageCache[StatusMessageCache_Size].delay_ms = 1500;
StatusMessageCache_Size++;
