set(_SOURCES
        Waypoint/CupWriter.cpp
        Waypoint/CupParser.cpp
        Waypoint/Factory.cpp
        Waypoint/HomeGlue.cpp
        Waypoint/LastUsed.cpp
        Waypoint/SaveGlue.cpp
        Waypoint/WaypointDetailsReader.cpp
        Waypoint/WaypointFileType.cpp
        Waypoint/WaypointFilter.cpp
        Waypoint/WaypointGlue.cpp
        Waypoint/WaypointList.cpp
        Waypoint/WaypointListBuilder.cpp
        Waypoint/WaypointReader.cpp
        Waypoint/WaypointReaderBase.cpp
        Waypoint/WaypointReaderCompeGPS.cpp
        Waypoint/WaypointReaderFS.cpp
        Waypoint/WaypointReaderOzi.cpp
        Waypoint/WaypointReaderSeeYou.cpp
        Waypoint/WaypointReaderWinPilot.cpp
        Waypoint/WaypointReaderZander.cpp
)

set(SCRIPT_FILES
    CMakeSource.cmake
)
