set(_SOURCES
        Gauge/BigThermalAssistantWidget.cpp
        Gauge/BigThermalAssistantWindow.cpp
        Gauge/BigTrafficWidget.cpp
        Gauge/FlarmTrafficWindow.cpp
        Gauge/GaugeFLARM.cpp
        Gauge/GaugeThermalAssistant.cpp
        Gauge/GaugeVario.cpp
        Gauge/GlueGaugeVario.cpp
        Gauge/LogoView.cpp
        Gauge/TaskView.cpp
        Gauge/ThermalAssistantRenderer.cpp
        Gauge/ThermalAssistantWindow.cpp
        Gauge/TrafficSettings.cpp
        Gauge/VarioSettings.cpp
)

set(SCRIPT_FILES
    CMakeSource.cmake
)
