/*
Copyright_License {

  XCSoar Glide Computer - http://www.xcsoar.org/
  Copyright (C) 2000-2014 The XCSoar Project
  A detailed list of copyright holders can be found in the file "AUTHORS".

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  as published by the Free Software Foundation; either version 2
  of the License, or (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
}
*/

#ifndef XCSOAR_TERRAIN_RASTER_WEATHER_STORE_HPP
#define XCSOAR_TERRAIN_RASTER_WEATHER_STORE_HPP

#include "Time/BrokenTime.hpp"
#include "Compiler.h"

#include <tchar.h>

class RasterMap;
class OperationEnvironment;
struct GeoPoint;
struct zzip_dir;

/**
 * Class to manage raster weather data.  Usually, these raster maps
 * are generated by RASP.
 */
class RasterWeatherStore {
public:
  static constexpr unsigned MAX_WEATHER_MAP = 16; /**< Max number of items stored */
  static constexpr unsigned MAX_WEATHER_TIMES = 48; /**< Max time segments of each item */

  struct MapInfo {
    const TCHAR *name;

    /**
     * Human-readable label.  Call gettext() for internationalization.
     */
    const TCHAR *label;

    /**
     * Human-readable help text.  Call gettext() for
     * internationalization.
     */
    const TCHAR *help;
  };

private:
  /**
   * Not protected by #lock because it's written only by ScanAll()
   * during startup.
   */
  bool weather_available[MAX_WEATHER_TIMES];

public:
  RasterWeatherStore();

  gcc_const
  static const MapInfo &GetItemInfo(unsigned i);

  /**
   * Load a list of RASP maps from the file "xcsoar-rasp.dat".
   */
  void ScanAll(const GeoPoint &location, OperationEnvironment &operation);

  bool IsTimeAvailable(unsigned time_index) const {
    return weather_available[time_index];
  }

  template<typename C>
  void ForEachTime(C &&c) const {
    for (unsigned i = 0; i < MAX_WEATHER_TIMES; ++i)
      if (weather_available[i])
        c(IndexToTime(i));
  }

  /**
   * Converts a time index to a #BrokenTime.
   */
  gcc_const
  static BrokenTime IndexToTime(unsigned index);

  static RasterMap *LoadItem(const TCHAR *name, unsigned time_index,
                             OperationEnvironment &operation);

private:
  static struct zzip_dir *OpenArchive();

  static void NarrowWeatherFilename(char *filename, const TCHAR *name,
                                    unsigned time_index);

  static void GetFilename(TCHAR *rasp_filename, const TCHAR *name,
                          unsigned time_index);

  gcc_pure
  static bool ExistsItem(struct zzip_dir *dir, const TCHAR *name,
                         unsigned time_index);
};

#endif
