//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by XCSoar.rc
//
#define IDS_APP_TITLE                   1
#define IDC_XCSOAR                      3
#define IDS_CONNECTWAIT                 4
#define IDI_XCSOAR                      101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDS_HELP                        104
#define IDD_PROGRESS                    104
#define IDD_SELECT                      106
#define IDD_TASK                        107
#define IDB_BITMAP1                     121
#define IDB_BITMAP2                     122
#define IDB_BITMAP3                     123
#define IDB_BITMAP4                     124
#define IDB_BITMAP5                     125
#define IDB_BITMAP6                     126
#define IDB_BITMAP7                     127
#define IDB_BITMAP8                     128
#define IDB_BITMAP9                     129
#define IDB_BITMAP10                    130
#define IDB_BITMAP11                    131
#define IDB_BITMAP12                    132
#define IDB_BITMAP13                    133
#define IDB_BITMAP14                    134
#define IDB_BITMAP15                    135
#define IDB_BITMAP16                    136
#define IDB_BITMAP17                    137
#define IDB_BITMAP18                    138
#define IDB_LANDABLE                    139
#define IDB_REACHABLE                   140
#define IDB_TURNPOINT                   141
#define IDB_SMALL                       142
#define IDD_REGISTER                    180
#define IDD_BUGSBALLAST                 181
#define IDD_AIRSPACE                    182
#define IDD_AIRSPACEALT                 183
#define IDD_AIRSPACEPRESS               184
#define IDD_WAYPOINTS                   185
#define IDD_TERRAIN                     186
#define IDD_UNITS                       187
#define IDD_PROFILELOAD                 188
#define IDD_PROFILESAVE                 189
#define IDD_COLOUR                      190
#define IDD_AIRSPACEWARN                191
#define IDD_COMM                        192
#define IDD_DISPLAY                     193
#define IDD_FGLIDE                      194
#define IDD_POLAR                       195
#define IDD_TASKSTART                   196
#define IDD_TASKSETTINGS                196
#define IDD_TASKTURN                    197
#define IDD_ASSIGNEDAREA                198
#define IDD_ASSIGNEDAREAFINISH          199
#define IDD_ASSIGNEDAREASTART           200
#define IDD_ASSIGNEDAREATURN            201
#define IDD_COLOURSEL                   202
#define IDM_MENU1                       203
#define IDD_MENU                        204
#define IDD_SETTINGS                    205
#define IDD_FILES                       207
#define IDD_AAT                         208
#define IDD_AATSTART                    209
#define IDD_AATFINISH                   210
#define IDD_AATTURN                     211
#define IDS_COMMAND1                    301
#define IDC_AAT                         1001
#define IDC_AATTIME                     1002
#define IDC_AATTIMESPIN                 1003
#define IDC_ADD                         1004
#define IDC_AIRSPACEFILE                1005
#define IDC_ALL                         1006
#define IDC_ALTITUDE_FEET               1007
#define IDC_ALTITUDE_METRES             1008
#define IDC_ALTTOL                      1009
#define IDC_ASSETNUMBER                 1010
#define IDC_AUTO                        1011
#define IDC_BALLAST                     1012
#define IDC_BITMAP0                     1013
#define IDC_BLUE                        1014
#define IDC_BM0                         1015
#define IDC_BM1                         1016
#define IDC_BM10                        1017
#define IDC_BM11                        1018
#define IDC_BM12                        1019
#define IDC_BM13                        1020
#define IDC_BM14                        1021
#define IDC_BM15                        1022
#define IDC_BM16                        1023
#define IDC_BM17                        1024
#define IDC_BM2                         1025
#define IDC_BM3                         1026
#define IDC_BM4                         1027
#define IDC_BM5                         1028
#define IDC_BM6                         1029
#define IDC_BM7                         1030
#define IDC_BM8                         1031
#define IDC_BM9                         1032
#define IDC_BROWSE                      1033
#define IDC_BUGS                        1034
#define IDC_BROWSETERRAIN               1034
#define IDC_BUTTON1                     1035
#define IDM_FILE                        1035
#define IDC_CHANGE                      1035
#define IDC_BROWSEWAYPOINT              1035
#define IDC_BUGSUP                      1035
#define IDC_DOWN                        1035
#define IDC_BUTTON10                    1036
#define IDM_FILE2                       1036
#define IDC_BALLASTUP                   1036
#define IDC_BUTTON11                    1037
#define IDM_PRESSUE                     1037
#define IDC_BUTTON12                    1038
#define IDM_SETTINGS                    1038
#define IDC_SETTINGS                    1038
#define IDC_BUTTON13                    1039
#define IDM_PRESSUE2                    1039
#define IDC_BUTTON14                    1040
#define IDC_BUTTON2                     1041
#define IDC_BUGSDOWN                    1041
#define IDC_UP                          1041
#define IDC_BUTTON3                     1042
#define IDC_BALLASTDOWN                 1042
#define IDC_BUTTON4                     1043
#define IDC_BUTTON5                     1044
#define IDC_BUTTON6                     1045
#define IDC_BUTTON7                     1046
#define IDC_BUTTON8                     1047
#define IDC_BUTTON9                     1048
#define IDC_CHECK4                      1049
#define IDC_CIRCLE                      1050
#define IDC_CLASSA                      1051
#define IDC_CLASSB                      1052
#define IDC_CLASSC                      1053
#define IDC_CLASSD                      1054
#define IDC_CLIMB                       1055
#define IDC_CLIP                        1056
#define IDC_CLIPALT                     1057
#define IDC_CLIPSPIN                    1058
#define IDC_COL                         1059
#define IDC_COMBO1                      1060
#define IDC_COMMPORT                    1061
#define IDC_CRUISE                      1062
#define IDC_CTR                         1063
#define IDC_CYLINDER                    1064
#define IDC_CYLINDERRADIUS              1065
#define IDC_DANGER                      1066
#define IDC_DISTANCE_METRIC             1067
#define IDC_DISTANCE_NAUTICAL           1068
#define IDC_DISTANCE_STATUTE            1069
#define IDC_EDIT                        1070
#define IDC_EDIT1                       1071
#define IDC_STARTRADIAL                 1071
#define IDC_EDIT2                       1072
#define IDC_FINISHRADIAL                1072
#define IDC_EDIT3                       1073
#define IDC_SECTORRADIUS                1073
#define IDC_EDIT4                       1074
#define IDC_CIRCLERADIUS                1074
#define IDC_EDIT9                       1075
#define IDC_EDITTEXT                    1076
#define IDC_EMPTY                       1077
#define IDC_ENABLE                      1078
#define IDC_END                         1079
#define IDC_ENDSPIN                     1080
#define IDC_EXTRA                       1081
#define IDC_FAI                         1082
#define IDC_FILE                        1083
#define IDC_GREEN                       1084
#define IDC_INHG                        1085
#define IDC_LD1                         1086
#define IDC_LD2                         1087
#define IDC_LD3                         1088
#define IDC_LIFT_KNOTS                  1089
#define IDC_LIFT_METRES                 1090
#define IDC_LIST1                       1091
#define IDC_LOAD                        1092
#define IDC_MARGINSPIN                  1093
#define IDC_MESSAGE                     1094
#define IDC_NEW                         1095
#define IDC_NOGLIDER                    1096
#define IDC_NORTHUP                     1097
#define IDC_OSVERSION                   1098
#define IDC_OTHER                       1099
#define IDC_PILOT                       1100
#define IDC_PORTSPEED                   1101
#define IDC_PROCESSOR                   1102
#define IDC_PROGRESS                    1103
#define IDC_PROHIBITED                  1104
#define IDC_QNH                         1105
#define IDC_QNHSPIN                     1106
#define IDC_RADIO1                      1107
#define IDC_BELOW                       1107
#define IDC_NORTHCIRCLE                 1107
#define IDC_RADIO2                      1108
#define IDC_RADIO3                      1109
#define IDC_RADIO4                      1110
#define IDC_RADIO5                      1111
#define IDC_RADIUS                      1112
#define IDC_RADIUSSPIN                  1113
#define IDC_RED                         1114
#define IDC_REGISTER                    1115
#define IDC_REGKEY                      1116
#define IDC_REMOVE                      1117
#define IDC_RESTRICTED                  1118
#define IDC_S1                          1119
#define IDC_S2                          1120
#define IDC_S3                          1121
#define IDC_SAFEALT                     1122
#define IDC_SALT                        1123
#define IDC_SALTB                       1124
#define IDC_SAVE                        1125
#define IDC_SCREEN                      1126
#define IDC_SECTOR                      1127
#define IDC_SELECT                      1128
#define IDC_SLIDER1                     1129
#define IDC_SNAIL                       1130
#define IDC_SPEED_METRIC                1131
#define IDC_SPEED_NAUTICAL              1132
#define IDC_SPEED_STATUTE               1133
#define IDC_SPIN1                       1134
#define IDC_SPIN2                       1135
#define IDC_SPIN3                       1136
#define IDC_SPIN4                       1137
#define IDC_SPIN6                       1138
#define IDC_SPIN7                       1139
#define IDC_SPIN8                       1140
#define IDC_SPINBALLAST                 1141
#define IDC_SPINBUGS                    1142
#define IDC_SPINEMPTY                   1143
#define IDC_SPINLD1                     1144
#define IDC_SPINLD2                     1145
#define IDC_SPINLD3                     1146
#define IDC_SPINPILOT                   1147
#define IDC_SPINS1                      1148
#define IDC_SPINV1                      1149
#define IDC_SPINV2                      1150
#define IDC_SPINV3                      1151
#define IDC_START                       1152
#define IDC_STARTCYLINDER               1153
#define IDC_STARTLINE                   1154
#define IDC_STARTSPIN                   1155
#define IDC_STATIC1                     1156
#define IDC_STATIC2                     1157
#define IDC_STATIC3                     1158
#define IDC_STATIC4                     1159
#define IDC_TAB                         1160
#define IDC_TAB1                        1161
#define IDC_SETTINGSTAB                 1161
#define IDC_TASK                        1162
#define IDC_TASKLENGTH                  1163
#define IDC_TERRAINFILE                 1164
#define IDC_TRACKUP                     1165
#define IDC_V1                          1166
#define IDC_V2                          1167
#define IDC_V3                          1168
#define IDC_WARNSPIN                    1169
#define IDC_WAVE                        1170
#define IDC_WAYPIONT                    1171
#define IDC_WAYPOINTFIRSTFIVE           1172
#define IDC_WAYPOINTFIRSTTHREE          1173
#define IDC_WAYPOINTLIST                1174
#define IDC_WAYPOINTNAME                1175
#define IDC_WAYPOINTNONE                1176
#define IDC_WAYPOINTNUMBERS             1177
#define IDC_WAYPOINTS                   1178
#define IDC_WAYPOINTSFILE               1179
#define IDD_BUGS                        1180
#define IDD_PRESSURE                    1181
#define IDD_AATASK                      1182
#define IDD_EXIT                        1183
#define IDC_POLAR                       1184
#define IDC_BROWSEAIRSPACE              1185
#define IDC_STARTRADIUS                 1186
#define IDD_LOCK                        1187
#define IDC_DISABLE                     1188
#define IDC_TIME                        1189
#define IDC_BUGSSCROLL                  1190
#define IDC_BALLASTSCROLL               1191
#define IDM_FILE_ABOUT                  40001
#define IDM_FILE_REGISTER               40002
#define IDM_FILE_LOCK                   40003
#define IDM_FILE_LOGGER                 40004
#define IDM_FILE_PROFILE_LOAD           40005
#define IDM_FILE_PROFILE_SAVE           40006
#define IDM_FILE_EXIT                   40007
#define IDM_BUGSBALLAST                 40008
#define IDS_LOCKWAIT                    40008
#define IDM_PRESSURE                    40009
#define IDM_BUGSBALLAST2                40009
#define IDM_SETTINGS_AIRSPACE_DISPLAY   40010
#define IDM_TASK                        40010
#define ID_MENUITEM40010                40010
#define IDD_BACK                        40010
#define IDM_SETTINGS_AIRSPACE_COLOUR    40011
#define IDM_TASK2                       40011
#define IDD_LOGGER                      40011
#define IDM_SETTINGS_AIRSPACE_WARNINGS  40012
#define IDS_CAP_MENUITEM40011           40012
#define IDM_SETTINGS_COMM               40013
#define IDM_SETTINGS_DISPLAY            40014
#define IDM_SETTINGS_FILES_AIRSPACE     40015
#define IDM_SETTINGS_FILES_TERRAIN      40016
#define IDM_SETTINGS_FILES_WAYPOINTS    40017
#define IDM_SETTINGS_FGLIDE             40018
#define IDM_SETTINGS_POLAR              40019
#define IDM_SETTINGS_TASK_START         40020
#define IDM_SETTINGS_TASK_TURN          40021
#define IDM_SETTINGS_UNITS              40022
#define IDM_TASK_TASK                   40023
#define IDM_TASK_ASSIGNEDAREA           40024

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1192
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
