//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by XCSoar.rc
//
#define IDS_APP_TITLE                   1
#define IDC_XCSOAR                      3
#define IDS_CONNECTWAIT                 4
#define IDI_XCSOAR                      101
#define IDM_MENU                        102
#define IDD_ABOUTBOX                    103
#define IDD_PROGRESS                    104
#define IDD_SELECT                      106
#define IDD_TASK                        107
#define IDB_BITMAP1                     121
#define IDB_BITMAP2                     122
#define IDB_BITMAP3                     123
#define IDB_BITMAP4                     124
#define IDB_BITMAP5                     125
#define IDB_BITMAP6                     126
#define IDB_BITMAP7                     127
#define IDB_BITMAP8                     128
#define IDB_BITMAP9                     129
#define IDB_BITMAP10                    130
#define IDB_BITMAP11                    131
#define IDB_BITMAP12                    132
#define IDB_BITMAP13                    133
#define IDB_BITMAP14                    134
#define IDB_BITMAP15                    135
#define IDB_BITMAP16                    136
#define IDB_BITMAP17                    137
#define IDB_BITMAP18                    138
#define IDB_LANDABLE                    139
#define IDB_REACHABLE                   140
#define IDB_TURNPOINT                   141
#define IDB_SMALL                       142
#define IDD_REGISTER                    180
#define IDD_BUGSBALLAST                 181
#define IDD_AIRSPACEALT                 183
#define IDD_AIRSPACEPRESS               184
#define IDD_UNITS                       187
#define IDD_PROFILELOAD                 188
#define IDD_PROFILESAVE                 189
#define IDD_COLOUR                      190
#define IDD_AIRSPACEWARN                191
#define IDD_COMM                        192
#define IDD_DISPLAY                     193
#define IDD_FGLIDE                      194
#define IDD_POLAR                       195
#define IDD_TASKSETTINGS                196
#define IDD_COLOURSEL                   202
#define IDM_MENU1                       203
#define IDD_MENU                        204
#define IDD_SETTINGS                    205
#define IDD_FILES                       207
#define IDD_AAT                         208
#define IDD_AATSTART                    209
#define IDD_AATFINISH                   210
#define IDD_AATTURN                     211
#define IDB_CRUISE                      212
#define IDB_CLIMB                       213
#define IDB_FINALGLIDE                  214
#define IDB_AUTOMCREADY                 215
#define IDD_WAYPOINTDETAILS             216
#define IDB_TOWN                        218
#define IDB_MARK                        219
#define IDB_TERRAINWARNING              220
#define IDI_XCSOARS                     223
#define IDD_LOGGERDETAILS               231
#define IDB_AIRSPACE                    235
#define IDD_AUDIO                       236
#define IDB_AIRSPACE0                   240
#define IDB_AIRSPACE1                   241
#define IDB_AIRSPACE2                   242
#define IDD_SPLASH                      243
#define IDB_SPLASH                      244
#define IDD_AIRSPACECOLOUR              247
#define IDD_AIRSPACECOLOURSEL           248
#define IDI_XCSOARSWIFT                 250
#define IDB_SWIFT                       251
#define IDD_GPSSTATUS                   252
#define IDC_AAT                         1001
#define IDC_AATTIME                     1002
#define IDC_AATTIMESPIN                 1003
#define IDC_ADD                         1004
#define IDC_AIRSPACEFILE                1005
#define IDC_ALL                         1006
#define IDC_ALTITUDE_FEET               1007
#define IDC_ALTITUDE_METRES             1008
#define IDC_ALTTOL                      1009
#define IDC_ASSETNUMBER                 1010
#define IDC_AUTO                        1011
#define IDC_BALLAST                     1012
#define IDC_BITMAP0                     1013
#define IDC_BLUE                        1014
#define IDC_BM0                         1015
#define IDC_BM1                         1016
#define IDC_BM2                         1017
#define IDC_BM3                         1018
#define IDC_BM4                         1019
#define IDC_BM5                         1020
#define IDC_BM6                         1021
#define IDC_BM7                         1022
#define IDC_BM8                         1023
#define IDC_BM9                         1024
#define IDC_BM10                        1025
#define IDC_BM11                        1026
#define IDC_BM12                        1027
#define IDC_BM13                        1028
#define IDC_BM14                        1029
#define IDC_BM15                        1030
#define IDC_BM16                        1031
#define IDC_BM17                        1032
#define IDC_BROWSE                      1033
#define IDC_BUGS                        1034
#define IDC_BROWSETERRAIN               1034
#define IDC_BROWSEWAYPOINT              1035
#define IDC_BUGSUP                      1035
#define IDC_DOWN                        1035
#define IDC_WAYPOINTDETAILSNEXT         1035
#define IDC_BALLASTUP                   1036
#define IDC_SETTINGS                    1038
#define IDC_BUGSDOWN                    1041
#define IDC_UP                          1041
#define IDC_BROWSEAIRFIELDS             1041
#define IDC_WDGOTO                      1041
#define IDC_BALLASTDOWN                 1042
#define IDC_WDREPLACE                   1042
#define IDC_BROWSETOPOLOGY              1042
#define IDC_WDSETHOME                   1043
#define IDC_WDINSERT                    1044
#define IDC_BROWSEPOLAR                 1045
#define IDC_CIRCLE                      1050
#define IDC_CLASSA                      1051
#define IDC_CLASSB                      1052
#define IDC_CLASSC                      1053
#define IDC_CLASSD                      1054
#define IDC_CLIP                        1056
#define IDC_CLIPALT                     1057
#define IDC_NAVBOXMODE                  1060
#define IDC_COMMPORT2                   1060
#define IDC_COMMPORT                    1061
#define IDC_NAVBOXOPTION                1062
#define IDC_DEVICE                      1062
#define IDC_CTR                         1063
#define IDC_DEVICE2                     1063
#define IDC_CYLINDER                    1064
#define IDC_CYLINDERRADIUS              1065
#define IDC_DANGER                      1066
#define IDC_DISTANCE_METRIC             1067
#define IDC_DISTANCE_NAUTICAL           1068
#define IDC_DISTANCE_STATUTE            1069
#define IDC_EDIT                        1070
#define IDC_STARTRADIAL                 1071
#define IDC_MAXSPEED                    1071
#define IDC_SALTBREAKOFF                1071
#define IDC_TOPOLOGYFILE                1071
#define IDC_FINISHRADIAL                1072
#define IDC_SALTTERRAIN                 1072
#define IDC_SECTORRADIUS                1073
#define IDC_AIRFIELDSFILE               1073
#define IDC_CIRCLERADIUS                1074
#define IDC_POLARFILE                   1074
#define IDC_ENABLE                      1078
#define IDC_EXTRA                       1081
#define IDC_FAI                         1082
#define IDC_FILE                        1083
#define IDC_INHG                        1085
#define IDC_LIFT_KNOTS                  1089
#define IDC_LIFT_METRES                 1090
#define IDC_LOAD                        1092
#define IDC_MESSAGE                     1094
#define IDC_DECLARE                     1094
#define IDC_NOGLIDER                    1096
#define IDC_NORTHUP                     1097
#define IDC_OSVERSION                   1098
#define IDC_OTHER                       1099
#define IDC_PORTSPEED                   1101
#define IDC_PROCESSOR                   1102
#define IDC_PROGRESS                    1103
#define IDC_PROHIBITED                  1104
#define IDC_QNH                         1105
#define IDC_BELOW                       1107
#define IDC_NORTHCIRCLE                 1107
#define IDC_WAYPOINTNAMEIFINTASK        1108
#define IDC_REGKEY                      1116
#define IDC_REMOVE                      1117
#define IDC_RESTRICTED                  1118
#define IDC_SALTARRIVAL                 1123
#define IDC_SALTB                       1124
#define IDC_SAVE                        1125
#define IDC_SECTOR                      1127
#define IDC_SNAIL                       1130
#define IDC_SPEED_METRIC                1131
#define IDC_SPEED_NAUTICAL              1132
#define IDC_SPEED_STATUTE               1133
#define IDC_STARTCYLINDER               1153
#define IDC_STARTLINE                   1154
#define IDC_STATIC1                     1156
#define IDC_STATIC2                     1157
#define IDC_STATIC3                     1158
#define IDC_TASK                        1162
#define IDC_TASKLENGTH                  1163
#define IDC_TERRAINFILE                 1164
#define IDC_TRACKUP                     1165
#define IDC_WAVE                        1170
#define IDC_WAYPOINTFIRSTFIVE           1172
#define IDC_WAYPOINTFIRSTTHREE          1173
#define IDC_WAYPOINTNAME                1175
#define IDC_WAYPOINTNONE                1176
#define IDC_WAYPOINTNUMBERS             1177
#define IDC_WAYPOINTS                   1178
#define IDC_WAYPOINTSFILE               1179
#define IDD_BUGS                        1180
#define IDD_PRESSURE                    1181
#define IDD_EXIT                        1183
#define IDC_POLAR                       1184
#define IDC_BROWSEAIRSPACE              1185
#define IDC_STARTRADIUS                 1186
#define IDD_LOCK                        1187
#define IDC_DISABLE                     1188
#define IDC_TIME                        1189
#define IDC_BALLASTSCROLL               1191
#define IDC_WAYPOINTDETAILSTEXT         1195
#define IDC_CIRCLEZOOM                  1196
#define IDC_PORTSPEED2                  1197
#define IDC_WDTEXT                      1198
#define IDC_DRAWTOPOLOGY                1199
#define IDC_DRAWTERRAIN                 1200
#define IDC_FINALGLIDETERRAIN           1201
#define IDC_WAYPOINTDETAILS             1202
#define IDC_PILOTNAME                   1204
#define IDC_AIRCRAFTTYPE                1206
#define IDC_AIRCRAFTREGO                1207
#define IDC_WDREMOVE                    1208
#define IDC_TRACKCIRCLE                 1209
#define IDC_AUDIOEVENTS                 1210
#define IDC_AUDIOUI                     1211
#define IDC_AUDIOSLIDER                 1212
#define IDC_AUDIODEADBAND               1213
#define IDC_AUDIOVARIO                  1214
#define IDC_ABORTTASK                   1215
#define IDC_ACKNOW                      1216
#define IDC_PALTITUDE                   1217
#define IDC_STATIC4                     1218
#define IDC_BM18                        1219
#define IDC_BM19                        1220
#define IDC_BM20                        1221
#define IDC_CHECK1                      1222
#define IDC_BLACKOUTLINE                1222
#define IDC_SPLASH                      1223
#define IDC_NETTOSPEED                  1224
#define IDC_UNDO                        1225
#define IDC_LISTAIRSPACE                1228
#define IDC_OK                          1230
#define IDC_CANCEL                      1231
#define IDC_PATTERN_BOX                 1234
#define IDC_COLOUR_BOX                  1235
#define IDC_AIRSPACE_CLASS              1236
#define IDC_BUTTON1                     1237
#define IDC_GPSMESSAGE                  1238
#define IDC_PROGRESS1                   1239
#define IDM_FILE_ABOUT                  40001
#define IDM_FILE_REGISTER               40002
#define IDM_FILE_LOCK                   40003
#define IDM_FILE_LOGGER                 40004
#define IDM_FILE_PROFILE_LOAD           40005
#define IDM_FILE_PROFILE_SAVE           40006
#define IDM_FILE_EXIT                   40007
#define IDM_BUGSBALLAST                 40008
#define IDS_LOCKWAIT                    40008
#define IDM_PRESSURE                    40009
#define IDM_SETTINGS_AIRSPACE_DISPLAY   40010
#define IDD_BACK                        40010
#define IDM_SETTINGS_AIRSPACE_COLOUR    40011
#define IDD_LOGGER                      40011
#define IDM_SETTINGS_AIRSPACE_WARNINGS  40012
#define IDM_SETTINGS_COMM               40013
#define IDM_SETTINGS_DISPLAY            40014
#define IDM_SETTINGS_FILES_AIRSPACE     40015
#define IDM_SETTINGS_FILES_TERRAIN      40016
#define IDM_SETTINGS_FILES_WAYPOINTS    40017
#define IDM_SETTINGS_FGLIDE             40018
#define IDM_SETTINGS_POLAR              40019
#define IDM_SETTINGS_TASK_START         40020
#define IDM_SETTINGS_TASK_TURN          40021
#define IDM_SETTINGS_UNITS              40022
#define IDM_TASK_TASK                   40023
#define IDM_TASK_ASSIGNEDAREA           40024

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         40025
#define _APS_NEXT_CONTROL_VALUE         1240
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
