/* Generated by Together */
#ifndef ABSTRACTTASK_H
#define ABSTRACTTASK_H

#include "TaskPoint.hpp"
#include "Util.h"
#include "TaskInterface.h"
#include "Tasks/TaskInterface.h"

class AbstractTask : TaskInterface {
public:
  AbstractTask(): activeTaskPoint(0) 
  {};

    unsigned getActiveTaskPointIndex();    

    double get_leg_bearing(const AIRCRAFT_STATE &);

    double get_leg_remaining(const AIRCRAFT_STATE &);

protected:
    unsigned activeTaskPoint;
};
#endif //ABSTRACTTASK_H
