/* Generated by Together */

#include "AbstractTask.h"
double AbstractTask::get_leg_remaining(const AIRCRAFT_STATE &ref)
{
  return ::Distance(ref.Location, getActiveTaskPoint()->
                    get_reference_remaining_destination());
}
double AbstractTask::get_leg_bearing(const AIRCRAFT_STATE &ref)
{
  return ::Bearing(ref.Location, getActiveTaskPoint()->
                   get_reference_remaining_destination());
}
unsigned AbstractTask::getActiveTaskPointIndex() 
{
  return activeTaskPoint;
}
