/* Generated by Together */

#include "GotoTask.h"

TaskPoint* GotoTask::getActiveTaskPoint() { 
  return tp;
}

void GotoTask::setActiveTaskPoint(unsigned index)
{
  // nothing to do
}


void GotoTask::report(const AIRCRAFT_STATE &state)
{

}

bool GotoTask::update_sample(const AIRCRAFT_STATE &state, 
                             const AIRCRAFT_STATE& state_last)
{
  return false; // nothing to do
}

