/* Generated by Together */

#ifndef GOTOTASK_H
#define GOTOTASK_H

#include "Tasks/AbstractTask.h"
struct Waypoint;

class GotoTask : public AbstractTask {
public:    
  GotoTask(const TaskEvents &te, 
           const TaskBehaviour &tb,
           TaskAdvance &ta,
           GlidePolar &gp);
  ~GotoTask();

  virtual TaskPoint* getActiveTaskPoint();
  virtual void setActiveTaskPoint(unsigned index);
  void do_goto(const Waypoint & wp);

#ifdef DO_PRINT
  virtual void print(const AIRCRAFT_STATE &state);
#endif

  virtual bool update_sample(const AIRCRAFT_STATE &, 
                             const bool full_update);
protected:
  virtual bool check_transitions(const AIRCRAFT_STATE &, 
                                 const AIRCRAFT_STATE&);

private:    
    TaskPoint* tp;
};

#endif //GOTOTASK_H
