/* Generated by Together */
class TaskPoint;

#ifndef GOTOTASK_H
#define GOTOTASK_H

#include "AbstractTask.h"
#include "Tasks/AbstractTask.h"

class GotoTask : public AbstractTask {
public:    

    virtual TaskPoint* getActiveTaskPoint() ;
private:    
    TaskPoint* tp;
};

#endif //GOTOTASK_H
