/* Generated by Together */

#ifndef GOTOTASK_H
#define GOTOTASK_H

#include "Tasks/AbstractTask.h"
#include <stdlib.h>

class GotoTask : public AbstractTask {
public:    
  GotoTask(): tp(NULL) 
  {};

    virtual TaskPoint* getActiveTaskPoint();
    virtual void setActiveTaskPoint(unsigned index);

  virtual void report(const AIRCRAFT_STATE &state);

  virtual bool update_sample(const AIRCRAFT_STATE &, const AIRCRAFT_STATE&);

private:    
    TaskPoint* tp;
};

#endif //GOTOTASK_H
