/* Generated by Together */

#ifndef TASKINTERFACE_H
#define TASKINTERFACE_H

struct AIRCRAFT_STATE;
struct GEOPOINT;
struct GeoVector;

class TaskStats;
class TaskPoint;

class TaskInterface {
public:

  virtual void setActiveTaskPoint(unsigned) = 0;
  
  virtual TaskPoint* getActiveTaskPoint() = 0;

  GeoVector get_active_vector(const AIRCRAFT_STATE &);

#ifdef DO_PRINT
  virtual void print(const AIRCRAFT_STATE &state) = 0;
#endif

  virtual bool update_idle(const AIRCRAFT_STATE &state) = 0;

  virtual bool update(const AIRCRAFT_STATE &, const AIRCRAFT_STATE&) = 0;

  virtual const TaskStats& get_stats() const = 0;

};
#endif //TASKINTERFACE_H
