/* Generated by Together */

#ifndef SPEEDLIMITZONE_H
#define SPEEDLIMITZONE_H

/**
 * \todo
 * - not yet used/implemented
 */
class SpeedLimitZone 
{
public:

    bool isInLimit();

protected:
    double maxSpeed;
};
#endif //SPEEDLIMITZONE_H
