#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright The XCSoar Project

"""Generate src/time/TimeZoneTable.cpp from the zoneinfo database.

Every TZif file (version 2 and newer) ends with a POSIX TZ string which
describes the rules that are in effect after the last transition stored
in the file, e.g. "CET-1CEST,M3.5.0,M10.5.0/3" for Europe/Berlin.  That
string is all XCSoar needs to calculate the UTC offset for any point in
time, so we copy it into a table instead of shipping (and parsing) the
database itself.

The strings are checked against the database before they are written:
this script evaluates them the same way src/time/PosixTimeZone.cpp does
and compares the result with the zoneinfo module.  It deliberately does
not ask the C library to do that, because the answer would then depend
on the platform: musl and the BSD libc that macOS uses reject the
negative transition times which Greenland needs.

Because a POSIX TZ string only describes the rules *after* the last
transition stored in the database, a zone with an announced rule change
(a region switching to permanent daylight saving time, say) is reported
as pending: the table anticipates the new rule from the day it is
generated.  Regenerate the table once the change has taken effect.

Run this script after a tzdata update:

  ./tools/GenerateTimeZones.py

Or, to verify that the checked-in table is still correct (this is what
the unit test cannot do, because it has no zoneinfo database):

  ./tools/GenerateTimeZones.py --check
"""

from __future__ import annotations

import argparse
import calendar
import struct
import sys
import zoneinfo
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ZONEINFO_DIR = Path('/usr/share/zoneinfo')

EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)

# Time zones whose daylight saving time cannot be expressed as a POSIX
# TZ string at all, because the transition dates are decided year by
# year: Morocco suspends daylight saving time during Ramadan, which
# moves through the calendar.  Users there have to configure a manual
# UTC offset.
UNREPRESENTABLE = frozenset((
    'Africa/Casablanca',
    'Africa/El_Aaiun',
))

OUTPUT_PATH = Path(__file__).resolve().parent.parent / 'src' / 'time' / 'TimeZoneTable.cpp'

HEADER = '''\
// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

/* This file was generated by tools/GenerateTimeZones.py from tzdata
   %s; do not edit it, regenerate it. */

#include "TimeZones.hpp"

static constexpr TimeZoneEntry time_zone_table[] = {
'''

FOOTER = '''};

std::span<const TimeZoneEntry>
GetTimeZones() noexcept
{
  return time_zone_table;
}
'''


class Transition:
    """One of the three date formats a POSIX TZ string may use for a
    daylight saving time transition."""

    def __init__(self, format, time, month=0, week=0, day_of_week=0, day=0):
        self.format = format
        self.time = time
        self.month = month
        self.week = week
        self.day_of_week = day_of_week
        self.day = day

    def get_date(self, year: int) -> date:
        if self.format == 'M':
            first = date(year, self.month, 1)
            # date.weekday() counts from Monday, POSIX from Sunday
            first_day_of_week = (first.weekday() + 1) % 7
            day = 1 + (self.day_of_week - first_day_of_week) % 7 \
                + (self.week - 1) * 7

            # "5" does not mean the fifth one, it always means the last
            last = calendar.monthrange(year, self.month)[1]
            while day > last:
                day -= 7

            return date(year, self.month, day)

        if self.format == 'J':
            # February 29 is never counted, i.e. day 60 is March 1 in
            # every year
            result = date(year, 1, 1) + timedelta(days=self.day - 1)
            if self.day >= 60 and calendar.isleap(year):
                result += timedelta(days=1)
            return result

        return date(year, 1, 1) + timedelta(days=self.day)


class PosixTimeZone:
    """A parsed POSIX TZ string; the counterpart of
    src/time/PosixTimeZone.cpp."""

    MAX_OFFSET_HOURS = 24
    MAX_TIME_HOURS = 167

    def __init__(self, standard_offset, daylight_offset=None,
                 daylight_start=None, daylight_end=None):
        self.standard_offset = standard_offset
        self.daylight_offset = daylight_offset
        self.daylight_start = daylight_start
        self.daylight_end = daylight_end

    @classmethod
    def parse(cls, s: str) -> 'PosixTimeZone':
        rest = cls._skip_abbreviation(s)

        # POSIX specifies the value which must be added to local time to
        # obtain UTC, which is the opposite of what everybody else writes
        standard_offset, rest = cls._parse_offset(rest, cls.MAX_OFFSET_HOURS)
        standard_offset = -standard_offset

        if not rest:
            return cls(standard_offset)

        rest = cls._skip_abbreviation(rest)

        if not rest or rest.startswith(','):
            # without an explicit offset, daylight saving time is one
            # hour ahead of standard time
            daylight_offset = standard_offset + 3600
        else:
            daylight_offset, rest = cls._parse_offset(rest,
                                                      cls.MAX_OFFSET_HOURS)
            daylight_offset = -daylight_offset

        if not rest.startswith(','):
            raise ValueError('daylight saving time without rules')

        start, rest = cls._parse_transition(rest[1:])
        if not rest.startswith(','):
            raise ValueError('missing second transition')

        end, rest = cls._parse_transition(rest[1:])
        if rest:
            raise ValueError(f'trailing garbage: {rest!r}')

        return cls(standard_offset, daylight_offset, start, end)

    def get_offset(self, t: datetime) -> int:
        """The UTC offset [seconds east of UTC] in effect at the given
        point in time."""

        if self.daylight_offset is None:
            return self.standard_offset

        # determine the year in local standard time
        year = (t + timedelta(seconds=self.standard_offset)).year

        start = self._instant(self.daylight_start, year, self.standard_offset)
        end = self._instant(self.daylight_end, year, self.daylight_offset)

        if start <= end:
            daylight = start <= t < end
        else:
            # southern hemisphere: daylight saving time spans the turn
            # of the year
            daylight = t >= start or t < end

        return self.daylight_offset if daylight else self.standard_offset

    def get_transitions(self, year: int) -> list[datetime]:
        if self.daylight_offset is None:
            return []

        return [
            self._instant(self.daylight_start, year, self.standard_offset),
            self._instant(self.daylight_end, year, self.daylight_offset),
        ]

    @staticmethod
    def _instant(transition: Transition, year: int, offset: int) -> datetime:
        d = transition.get_date(year)
        return datetime(d.year, d.month, d.day, tzinfo=timezone.utc) \
            + timedelta(seconds=transition.time - offset)

    @staticmethod
    def _skip_abbreviation(s: str) -> str:
        if s.startswith('<'):
            end = s.find('>')
            if end < 4:
                raise ValueError(f'malformed abbreviation: {s!r}')
            return s[end + 1:]

        length = 0
        while length < len(s) and s[length].isascii() and s[length].isalpha():
            length += 1

        if length < 3:
            raise ValueError(f'malformed abbreviation: {s!r}')

        return s[length:]

    @staticmethod
    def _parse_unsigned(s: str, max_digits: int) -> tuple[int, str]:
        length = 0
        while length < len(s) and length < max_digits and s[length].isdigit():
            length += 1

        if length == 0:
            raise ValueError(f'number expected: {s!r}')

        return int(s[:length]), s[length:]

    @classmethod
    def _parse_offset(cls, s: str, max_hours: int) -> tuple[int, str]:
        negative = s.startswith('-')
        if negative or s.startswith('+'):
            s = s[1:]

        hours, s = cls._parse_unsigned(s, 3)
        if hours > max_hours:
            raise ValueError(f'offset out of range: {hours}')

        minutes = seconds = 0

        if s.startswith(':'):
            minutes, s = cls._parse_unsigned(s[1:], 2)
            if minutes > 59:
                raise ValueError(f'minutes out of range: {minutes}')

            if s.startswith(':'):
                seconds, s = cls._parse_unsigned(s[1:], 2)
                if seconds > 59:
                    raise ValueError(f'seconds out of range: {seconds}')

        value = hours * 3600 + minutes * 60 + seconds
        return -value if negative else value, s

    @classmethod
    def _parse_transition(cls, s: str) -> tuple[Transition, str]:
        if s.startswith('M'):
            month, s = cls._parse_unsigned(s[1:], 2)
            if not 1 <= month <= 12 or not s.startswith('.'):
                raise ValueError(f'malformed month rule: {s!r}')

            week, s = cls._parse_unsigned(s[1:], 1)
            if not 1 <= week <= 5 or not s.startswith('.'):
                raise ValueError(f'malformed week rule: {s!r}')

            day_of_week, s = cls._parse_unsigned(s[1:], 1)
            if day_of_week > 6:
                raise ValueError(f'malformed weekday rule: {s!r}')

            kwargs = dict(month=month, week=week, day_of_week=day_of_week)
            format = 'M'
        elif s.startswith('J'):
            day, s = cls._parse_unsigned(s[1:], 3)
            if not 1 <= day <= 365:
                raise ValueError(f'julian day out of range: {day}')

            kwargs = dict(day=day)
            format = 'J'
        else:
            day, s = cls._parse_unsigned(s, 3)
            if day > 365:
                raise ValueError(f'day of year out of range: {day}')

            kwargs = dict(day=day)
            format = 'n'

        # POSIX specifies 02:00:00 as the default
        time = 2 * 3600
        if s.startswith('/'):
            time, s = cls._parse_offset(s[1:], cls.MAX_TIME_HOURS)

        return Transition(format, time, **kwargs), s


def read_zone_ids(directory: Path) -> list[str]:
    """Read the zone ids from zone.tab, which lists one zone per country
    and therefore contains the names people expect to find."""

    ids = {'UTC'}

    with (directory / 'zone.tab').open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            columns = line.split('\t')
            if len(columns) >= 3:
                ids.add(columns[2])

    return sorted(ids)


def read_tzif(path: Path) -> tuple[str, datetime | None]:
    """Extract the POSIX TZ string and the last transition stored in a
    TZif file."""

    data = path.read_bytes()
    if not data.startswith(b'TZif'):
        raise ValueError('not a TZif file')

    if data[4:5] == b'\0':
        raise ValueError('TZif version 1 has no POSIX TZ string')

    def counts(offset):
        # isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt
        return struct.unpack('>6I', data[offset + 20:offset + 44])

    isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt = counts(0)

    # skip the version 1 block, which is present for compatibility only
    offset = 44 + timecnt * 5 + typecnt * 6 + charcnt + leapcnt * 8 \
        + isstdcnt + isutcnt
    if data[offset:offset + 4] != b'TZif':
        raise ValueError('no version 2 header')

    isutcnt, isstdcnt, leapcnt, timecnt, typecnt, charcnt = counts(offset)
    offset += 44

    last_transition = None
    if timecnt > 0:
        seconds, = struct.unpack('>q',
                                 data[offset + (timecnt - 1) * 8:
                                      offset + timecnt * 8])
        last_transition = EPOCH + timedelta(seconds=seconds)

    offset += timecnt * 9 + typecnt * 6 + charcnt + leapcnt * 12 \
        + isstdcnt + isutcnt

    if data[offset:offset + 1] != b'\n':
        raise ValueError('no POSIX TZ string')

    end = data.index(b'\n', offset + 1)
    posix = data[offset + 1:end].decode('ascii')
    if not posix:
        raise ValueError('empty POSIX TZ string')

    return posix, last_transition


def verify(zone_id: str, posix: str, last_transition: datetime | None,
           years: int = 5) -> tuple[list[str], list[str]]:
    """Compare the POSIX TZ string against the zoneinfo database, from
    now until a few years from now.  Returns the mismatches which are
    errors and those which are an announced rule change the string
    already anticipates."""

    tz = PosixTimeZone.parse(posix)
    zone = zoneinfo.ZoneInfo(zone_id)

    now = datetime.now(timezone.utc)
    errors, pending = [], []

    def compare(t):
        expected = t.astimezone(zone).utcoffset()
        actual = timedelta(seconds=tz.get_offset(t))
        if expected == actual:
            return

        message = (f'{zone_id}: {t:%Y-%m-%d %H:%M}: {posix} yields {actual}, '
                   f'expected {expected}')

        if last_transition is not None and t < last_transition:
            pending.append(message)
        else:
            errors.append(message)

    # a daily sample finds a transition which moved to another date
    for i in range(3 * 365):
        compare(now + timedelta(days=i))

    # the transitions themselves find one which moved by hours only
    for year in range(now.year, now.year + years + 1):
        for t in tz.get_transitions(year):
            if t > now:
                compare(t - timedelta(minutes=1))
                compare(t + timedelta(minutes=1))

    return errors, pending


def read_version(directory: Path) -> str:
    # the BSD and macOS databases carry their version in +VERSION
    path = directory / '+VERSION'
    if path.exists():
        version = path.read_text().strip()
        if version:
            return 'version ' + version

    # the tzdata distribution states it in the first line of tzdata.zi
    path = directory / 'tzdata.zi'
    if path.exists():
        with path.open() as f:
            first = f.readline().strip()
            if first.startswith('#'):
                return first.lstrip('# ')

    return 'of unknown version'


def generate(directory: Path, skip_verify: bool) -> str:
    entries = []
    errors = []
    pending = []

    for zone_id in read_zone_ids(directory):
        if zone_id in UNREPRESENTABLE:
            continue

        try:
            posix, last_transition = read_tzif(directory / zone_id)

            if not skip_verify:
                zone_errors, zone_pending = verify(zone_id, posix,
                                                   last_transition)
                errors += zone_errors
                pending += zone_pending
        except (OSError, ValueError, zoneinfo.ZoneInfoNotFoundError) as e:
            errors.append(f'{zone_id}: {e}')
            continue

        entries.append((zone_id, posix))

    if pending:
        zones = sorted({i.split(':')[0] for i in pending})
        print('the rules of these zones are about to change; the table '
              'anticipates the new ones: ' + ', '.join(zones), file=sys.stderr)

    if errors:
        for i in errors:
            print(i, file=sys.stderr)
        raise SystemExit('the zoneinfo database and this script disagree')

    width = max(len(i[0]) for i in entries) + 3

    body = ''.join('  { %s %s },\n' % (f'"{zone_id}",'.ljust(width),
                                       f'"{posix}"')
                   for zone_id, posix in entries)

    return (HEADER % read_version(directory)) + body + FOOTER


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='only check whether the table is up to date')
    parser.add_argument('--no-verify', action='store_true',
                        help='do not compare the strings against tzdata')
    parser.add_argument('--zoneinfo', type=Path, default=ZONEINFO_DIR,
                        help='path of the zoneinfo database')
    args = parser.parse_args()

    generated = generate(args.zoneinfo, args.no_verify)

    if args.check:
        if OUTPUT_PATH.read_text() != generated:
            raise SystemExit(f'{OUTPUT_PATH} is out of date; '
                             'run tools/GenerateTimeZones.py')
        print(f'{OUTPUT_PATH} is up to date')
    else:
        OUTPUT_PATH.write_text(generated)
        print(f'wrote {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
