/* Generated by Together */

#include "CylinderZone.hpp"
#include <math.h>
#include "Util.h"

GEOPOINT CylinderZone::get_boundary_parametric(double t) 
{ 
  // todo: should be findlocation
  GEOPOINT loc = getLocation();
  loc.Longitude += Radius*cos(t*3.1415926*2.0);
  loc.Latitude += Radius*sin(t*3.1415926*2.0);
  return loc;
}
