/* Generated by Together */

#include "SectorZone.hpp"
#include <math.h>

GEOPOINT SectorZone::get_boundary_parametric(double t) 
{ 
  // todo: should be findlocation
  GEOPOINT loc = getLocation();
  double ang = t*3.1415926*2.0;
  loc.Longitude += Radius*cos(ang);
  loc.Latitude += Radius*sin(ang);
  if (isInSector(loc)) {
    return loc;
  } else {
    return getLocation();
  }
}
