import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

// Serve the manual figures and map icons straight from the repository
// instead of keeping copies in docs/public. Paths must be absolute because
// nitro resolves relative publicAssets dirs against its own srcDir.
const repo = (path: string) => fileURLToPath(new URL(path, import.meta.url));

// Runs git in the repository without a shell; '' when git or the
// repository is missing.
const git = (...args: string[]) => {
    try {
        return execFileSync('git', args, { cwd: repo('..'), stdio: ['ignore', 'pipe', 'ignore'] })
            .toString().trim();
    } catch {
        return '';
    }
};

// Commit of the documentation build, shown on the PDF title page.
const xcsoarCommit = git('rev-parse', '--short=12', 'HEAD');

// Like the XCSoar build system: a commit tagged v<version> is the release
// of that version, anything else a development build without a version.
const xcsoarVersion = git('tag', '--points-at', 'HEAD').split('\n')
    .map(tag => /^v(\d[\w.]*)$/.exec(tag)?.[1])
    .find(Boolean) ?? '';

// Staged or unstaged changes below docs/: the build matches no commit.
const xcsoarDirty = git('status', '--porcelain', '--untracked-files=no', '--', 'docs') !== '';

// Last commit of every content file (author, not committer) and its
// position in the history, 0 being the newest commit, from one walk of
// the history below docs/content.
type Commit = { commit: string, date: string, author: string };
let commits: Map<string, { last: Commit, position: number }> | undefined;
const fileCommit = (path: string) => {
    if (!commits) {
        commits = new Map();
        let current: Commit | undefined;
        let position = -1;
        for (const line of git('log', '--format=@%H %as %an', '--name-only', '--', 'docs/content', 'docs/content-history.json').split('\n')) {
            if (line.startsWith('@')) {
                const [commit, date, ...author] = line.slice(1).split(' ');
                current = { commit, date, author: author.join(' ') };
                position++;
            } else if (line && current && !commits.has(line)) {
                commits.set(line, { last: current, position });
            }
        }
    }
    return commits.get(relative(repo('..'), path));
};

// Pages migrated from the LaTeX manual, the RST developer docs or the
// InfoBox sources show the last commit of that source, collected by
// scripts/import-history.mjs, unless the page was changed after the
// last commit of content-history.json.
const history: Record<string, Commit> = JSON.parse(readFileSync(repo('content-history.json'), 'utf8'));
const lastCommit = (path: string) => {
    const own = fileCommit(path);
    const migrated = history[relative(repo('content'), path)];
    const historyPosition = fileCommit(repo('content-history.json'))?.position ?? -1;
    if (migrated && (!own || own.position >= historyPosition)) {
        const { commit, date, author } = migrated;
        return { commit, date, author };
    }
    return own?.last;
};

// Permalinks: a page the XCSoar app links to declares "permalink: <id>" in
// its frontmatter, and /go/<id> redirects to the page (an anchor appended
// by the caller survives the redirect). Apache serves the redirects from
// .htaccess, as 302 so that a changed target is not cached by browsers.
// The pages are read from disk, not from the parsed content, because Nuxt
// Content parses only the pages that changed since the last build.
const permalinks = () => {
    const content = repo('content');
    const ids = new Map<string, string>();
    const errors: string[] = [];
    for (const file of readdirSync(content, { recursive: true, encoding: 'utf8' }).sort()) {
        if (!file.endsWith('.md')) continue;
        const text = readFileSync(join(content, file), 'utf8');
        const id = /^---\n(?:.*\n)*?permalink:[ \t]*(.*?)[ \t]*\n(?:.*\n)*?---\n/.exec(text)?.[1];
        if (id === undefined) continue;
        const path = '/' + file.replace(/\.md$/, '').split('/')
            .map(segment => segment.replace(/^\d+\./, ''))
            .filter((segment, i, all) => !(i === all.length - 1 && segment === 'index'))
            .join('/');
        if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) errors.push(`${file}: permalink "${id}" must be lower-case letters, digits and hyphens`);
        else if (ids.has(id)) errors.push(`${file}: permalink "${id}" is already used by ${ids.get(id)}`);
        else ids.set(id, path);
    }
    if (errors.length) throw new Error(errors.join('\n'));
    return [
        '# Generated by nuxt.config.ts from the permalink frontmatter of the pages.',
        ...[...ids].map(([id, path]) => `RedirectMatch 302 ^/go/${id}$ ${path}`),
        '',
    ].join('\n');
};

export default defineNuxtConfig({
    devtools: false,
    extends: ['docus'],
    hooks: {
        // The landing page gets the docs layout, which shows the row of
        // sections below the header; app/layouts/docs.vue leaves out the
        // sidebar for it.
        'pages:resolved'(pages) {
            const landing = pages.find(page => page.path === '/');
            if (landing) landing.meta = { ...landing.meta, layout: 'docs' };
        },
        // The licence page shows COPYING verbatim, not parsed as markdown.
        // Append the last commit of the page to its body; PageMeta.vue
        // renders it below the content. The landing page has none.
        'content:file:afterParse'({ file, content }) {
            const body = content.body as { type?: string, value?: unknown[] } | undefined;
            if (body?.type === 'minimark' && content.stem === '1.manual/15.license') {
                body.value = [['pre', { copy: false, class: 'license' }, readFileSync(repo('../COPYING'), 'utf8')]];
            }
            const last = body?.type === 'minimark' && content.stem !== 'index' ? lastCommit(file.path) : undefined;
            if (last) body.value!.push(['page-meta', last]);
        },
        // Written before prerendering, which fails the build early on a
        // duplicate or invalid permalink.
        'nitro:build:public-assets'(nitro) {
            writeFileSync(join(nitro.options.output.publicDir, '.htaccess'), permalinks());
        },
    },
    app: {
        head: {
            script: [
                {
                    // Static hosts redirect "/manual/preface" to
                    // "/manual/preface/", but the page was prerendered
                    // without the slash. Drop it before Nuxt boots so the
                    // prerendered payload is reused on hydration.
                    innerHTML: "if (location.pathname.length > 1 && location.pathname.endsWith('/')) history.replaceState(null, '', location.pathname.replace(/\\/+$/, '') + location.search + location.hash)",
                },
            ],
        },
    },
    content: {
        build: {
            markdown: {
                highlight: {
                    // Docus ships only web languages; the developer docs
                    // also show C++, Lua, XML and make snippets.
                    langs: ['cpp', 'lua', 'xml', 'make'],
                },
                // Nuxt Content caches parsed pages by file content and
                // these options. The commit makes every page re-parse after
                // a new commit, so the last-commit line below the page (see
                // hooks) does not go stale.
                ...({ gitHead: xcsoarCommit } as object),
            },
        },
    },
    image: {
        // Figures come from nitro publicAssets outside docs/public, which the
        // IPX optimizer cannot read. Serve image URLs unchanged instead.
        provider: 'none',
    },
    runtimeConfig: {
        public: {
            xcsoarVersion,
            xcsoarCommit,
            xcsoarDirty,
        },
    },
    routeRules: {
        // Print views for scripts/build-pdf.mjs, not for search engines.
        '/print/**': { robots: false },
    },
    nitro: {
        prerender: {
            autoSubfolderIndex: true,
            routes: ['/print/manual', '/print/quick-guide', '/print/dev'],
        },
        publicAssets: [
            { baseURL: '/img/figures', dir: repo('../doc/manual/en/figures') },
            { baseURL: '/img/drawings', dir: repo('../doc/manual/figures') },
            { baseURL: '/img/icons', dir: repo('../Data/icons') },
            { baseURL: '/img/graphics', dir: repo('../Data/graphics') },
        ],
    },
});
