#define IDI_XCSOAR                      101
#define IDD_PROGRESS                    104
#define IDB_LANDABLE                    139
#define IDB_LANDABLE_HD                5139
#define IDB_REACHABLE                   140
#define IDB_REACHABLE_HD               5140
#define IDB_TURNPOINT                   141
#define IDB_TURNPOINT_HD               5141
#define IDB_SMALL                       142
#define IDB_SMALL_HD                   5142
#define IDB_CRUISE                      212
#define IDB_CRUISE_HD                  5212
#define IDB_CLIMB                       213
#define IDB_CLIMB_HD                   5213
#define IDB_FINALGLIDE                  214
#define IDB_FINALGLIDE_HD              5214
#define IDB_TOWN                        218
#define IDB_TOWN_HD                    5218
#define IDB_MARK                        219
#define IDB_MARK_HD                    5219
#define IDB_TERRAINWARNING              220
#define IDB_TERRAINWARNING_HD          5220
#define IDB_AIRSPACE                    235
#define IDB_AIRSPACE0                   240
#define IDB_AIRSPACE1                   241
#define IDB_AIRSPACE2                   242
#define IDB_SWIFT_HD                    251
#define IDB_GPSSTATUS1                  256
#define IDB_GPSSTATUS1_HD              5256
#define IDB_GPSSTATUS2                  257
#define IDB_GPSSTATUS2_HD              5257
#define IDD_PROGRESS_LANDSCAPE          265
#define IDB_ABORT                       269
#define IDB_ABORT_HD                   5269
#define IDB_LOGGER                      271
#define IDB_LOGGER_HD                  5271
#define IDB_LOGGEROFF                   272
#define IDB_LOGGEROFF_HD               5272
#define IDB_FLARMTRAFFIC                278
#define IDB_FLARMTRAFFIC_HD            5278
#define IDB_AIRSPACE3                   280
#define IDB_DLGBUTTONLEFT32             282
#define IDB_UNIT_KM                     284
#define IDB_UNIT_SM                     285
#define IDB_UNIT_NM                     286
#define IDB_UNIT_M                      287
#define IDB_UNIT_FT                     288
#define IDB_AIRPORT_REACHABLE           289
#define IDB_AIRPORT_REACHABLE_HD       5289
#define IDB_AIRPORT_UNREACHABLE         290
#define IDB_AIRPORT_UNREACHABLE_HD     5290
#define IDB_OUTFIELD_REACHABLE          291
#define IDB_OUTFIELD_REACHABLE_HD      5291
#define IDB_OUTFIELD_UNREACHABLE        292
#define IDB_OUTFIELD_UNREACHABLE_HD    5292
#define IDB_VARIOSCALEA                 293
#define IDB_UNIT_MS                     294
#define IDB_UNIT_KT                     295
#define IDB_UNIT_FL                     296
#define IDB_UNIT_DegK                   297
#define IDB_UNIT_DegC                   298
#define IDB_UNIT_DegF                   299
#define IDB_UNIT_FPM                    300
#define IDB_UNIT_KMH                    301
#define IDB_UNIT_MPH                    302
#define IDB_DLGBUTTONRIGHT32            304
#define IDB_AIRSPACE4                   306
#define IDB_AIRSPACE5                   311
#define IDB_CLIMBSMALL                  313
#define IDB_CLIMBSMALLINV               314
#define IDB_VARIOSCALEC                 315
#define IDB_THERMALSOURCE               316
#define IDB_THERMALSOURCE_HD           5316
#define IDB_AIRSPACE6                   317
#define IDB_AIRSPACE7                   318
#define IDB_TARGET                      320
#define IDB_TARGET_HD                  5320
#define IDB_ABOVETERRAIN                321
#define IDB_TEAMMATE_POS                322
#define IDB_TEAMMATE_POS_HD            5322
#define IDB_LAUNCHER1                   330
#define IDB_LAUNCHER2                   331
#define IDB_SWIFT                       332
#define IDD_PROGRESS_LANDSCAPE2         333
#define IDB_AIRPORT_UNREACHABLE2        334
#define IDB_AIRPORT_UNREACHABLE2_HD    5334
#define IDB_OUTFIELD_UNREACHABLE2       335
#define IDB_OUTFIELD_UNREACHABLE2_HD   5335
#define IDB_AIRSPACEI                   336
#define IDB_AIRSPACEI_HD               5336
#define IDB_PROGRESSBORDER              337
#define IDB_TITLE                       338
#define IDB_TITLE_HD                    339
#define IDB_MAPSCALE_LEFT               340
#define IDB_MAPSCALE_RIGHT              341
#define IDB_MAPSCALE_LEFT_HD           5340
#define IDB_MAPSCALE_RIGHT_HD          5341
#define IDB_DIALOGTITLE                 342
#define IDB_MOUNTAIN_TOP                343
#define IDB_MOUNTAIN_TOP_HD            5343
#define IDB_BRIDGE                      344
#define IDB_BRIDGE_HD                  5344
#define IDB_TUNNEL                      345
#define IDB_TUNNEL_HD                  5345
#define IDB_TOWER                       346
#define IDB_TOWER_HD                   5346
#define IDB_POWER_PLANT                 347
#define IDB_POWER_PLANT_HD             5347
#define IDB_FOLDER                      348
#define IDB_FOLDER_HD                  5348
#define IDB_SETTINGS                    349
#define IDB_SETTINGS_HD                5349
#define IDB_TASK                        350
#define IDB_TASK_HD                    5350
#define IDB_CALCULATOR                  351
#define IDB_CALCULATOR_HD              5351
#define IDB_AIRPORT_MARGINAL            352
#define IDB_AIRPORT_MARGINAL_HD        5352
#define IDB_OUTFIELD_MARGINAL           353
#define IDB_OUTFIELD_MARGINAL_HD       5353
#define IDB_AIRPORT_MARGINAL2           354
#define IDB_AIRPORT_MARGINAL2_HD       5354
#define IDB_OUTFIELD_MARGINAL2          355
#define IDB_OUTFIELD_MARGINAL2_HD      5355
#define IDB_MARGINAL                    356
#define IDB_MARGINAL_HD                5356
#define IDB_WRENCH                      357
#define IDB_WRENCH_HD                  5357
#define IDB_GLOBE                       358
#define IDB_GLOBE_HD                   5358
#define IDB_DEVICE                      359
#define IDB_DEVICE_HD                  5359
#define IDB_RULES                       360
#define IDB_RULES_HD                   5360
#define IDB_CLOCK                       361
#define IDB_CLOCK_HD                   5361
#define IDB_TRAFFIC_SAFE                362
#define IDB_TRAFFIC_SAFE_HD            5362
#define IDB_TRAFFIC_WARNING             363
#define IDB_TRAFFIC_WARNING_HD         5363
#define IDB_TRAFFIC_ALARM               364
#define IDB_TRAFFIC_ALARM_HD           5364
#define IDB_TASKTURNPOINT               365
#define IDB_TASKTURNPOINT_HD           5365
#define IDB_OBSTACLE                    366
#define IDB_OBSTACLE_HD                5366
