#ifndef TOLERANCES_HPP
#define TOLERANCES_HPP

#define TOLERANCE_MC_OPT_GLIDE 0.1
#define TOLERANCE_POLAR_BESTLD 0.1
#define TOLERANCE_ISOLINE_CROSSING 0.0001
#define TOLERANCE_CRUISE_EFFICIENCY 0.01
#define TOLERANCE_BEST_MC 0.0001
#define TOLERANCE_GLIDE_REQUIRED 0.001
#define TOLERANCE_MIN_TARGET 0.002
#define TOLERANCE_OPT_TARGET 0.01

#endif
