/* Generated by Together */

#include "CylinderZone.hpp"
#include "Navigation/Geometry/GeoVector.hpp"
#include <stdlib.h>
#include <algorithm>

double CylinderZone::score_adjustment() const
{
  return Radius;
}

GEOPOINT CylinderZone::get_boundary_parametric(double t) const
{ 
  return GeoVector(Radius, t*360).end_point(get_location());
}

bool
CylinderZone::equals(const ObservationZonePoint* other) const
{
  if (ObservationZonePoint::equals(other)) {
    if (const CylinderZone* z = dynamic_cast<const CylinderZone*>(other)) {
      return Radius == z->getRadius();
    }
  }
  return false;
}

GEOPOINT
CylinderZone::randomPointInSector(const double mag) const
{
  AIRCRAFT_STATE ac;  
  do {

    double dir = rand()%360;
    double dmag = std::max(std::min(Radius,100.0), Radius*mag);
    double dis = (0.1+(rand()%90)/100.0)*dmag;
    GeoVector vec(dis,dir);
    ac.Location = vec.end_point(get_location());
  } while (!isInSector(ac));
  return ac.get_location();
}
