import { defineNuxtModule } from '@nuxt/kit';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Permalinks: a page the XCSoar app links to declares "permalink: <id>" in
// its frontmatter, and /go/<id> redirects to the page (an anchor appended
// by the caller survives the redirect). Apache serves the redirects from
// .htaccess, as 302 so that a changed target is not cached by browsers.
// The pages are read from disk, not from the parsed content, because Nuxt
// Content parses only the pages that changed since the last build.
// A duplicate or invalid id throws before prerendering and fails the build.
const htaccess = (content: string) => {
    const ids = new Map<string, string>();
    const errors: string[] = [];
    for (const file of readdirSync(content, { recursive: true, encoding: 'utf8' }).sort()) {
        if (!file.endsWith('.md')) continue;
        const text = readFileSync(join(content, file), 'utf8');
        const id = /^---\n(?:.*\n)*?permalink:[ \t]*(.*?)[ \t]*\n(?:.*\n)*?---\n/.exec(text)?.[1];
        if (id === undefined) continue;
        const path = '/' + file.replace(/\.md$/, '').split('/')
            .map(segment => segment.replace(/^\d+\./, ''))
            .filter((segment, i, all) => !(i === all.length - 1 && segment === 'index'))
            .join('/');
        if (!/^[a-z0-9][a-z0-9-]*$/.test(id)) errors.push(`${file}: permalink "${id}" must be lower-case letters, digits and hyphens`);
        else if (ids.has(id)) errors.push(`${file}: permalink "${id}" is already used by ${ids.get(id)}`);
        else ids.set(id, path);
    }
    if (errors.length) throw new Error(errors.join('\n'));
    return [
        '# Generated by modules/permalinks.ts from the permalink frontmatter of the pages.',
        ...[...ids].map(([id, path]) => `RedirectMatch 302 ^/go/${id}$ ${path}`),
        '',
    ].join('\n');
};

export default defineNuxtModule({
    meta: { name: 'permalinks' },
    setup(_, nuxt) {
        nuxt.hook('nitro:build:public-assets', (nitro) => {
            writeFileSync(join(nitro.options.output.publicDir, '.htaccess'), htaccess(join(nuxt.options.rootDir, 'content')));
        });
    },
});
