// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright The XCSoar Project

#pragma once

#include "ui/dim/BulkPoint.hpp"

#include <span>

/**
 * One closed polygon of a traffic symbol in template space: the
 * 28-unit icon box spans -500..+500 on both axes (see
 * #AIRCRAFT_TYPE_SYMBOL_SPAN), north (direction of travel) is up.
 */
struct AircraftTypeSymbolPolygon {
  std::span<const BulkPixelPoint> points;

  /**
   * Is this a hole or highlight inside the shape?  Holes in the glyph
   * show the halo colour again.
   */
  bool hole;
};

/**
 * The symbol of one FLARM aircraft type: a halo silhouette and the
 * glyph drawn on top of it; see #AircraftTypeSymbolStyle for how the
 * two are coloured.
 *
 * The tables are generated by tools/GenerateTrafficSymbols.py from
 * the SVG icons in Data/icons/traffic.
 */
struct AircraftTypeSymbol {
  std::span<const AircraftTypeSymbolPolygon> halo;
  std::span<const AircraftTypeSymbolPolygon> glyph;

  constexpr bool IsDefined() const noexcept {
    return !halo.empty();
  }
};

/**
 * The template box of #aircraft_type_symbols spans this many units;
 * a symbol drawn with a box of N pixels is scaled by N / SPAN.
 */
static constexpr int AIRCRAFT_TYPE_SYMBOL_SPAN = 1000;

/**
 * Largest polygon in #aircraft_type_symbols; keep in sync with
 * MAX_POINTS in tools/GenerateTrafficSymbols.py.
 */
static constexpr std::size_t MAX_AIRCRAFT_TYPE_SYMBOL_POINTS = 96;

/**
 * Indexed by FlarmTraffic::AircraftType.  Unknown, flying saucer and
 * reserved share the generic "unknown" symbol.
 */
extern const AircraftTypeSymbol aircraft_type_symbols[16];
