on:
  workflow_dispatch:
  push:
    paths:
      - ./ide/docker/
      - ./ide/provisioning/

jobs:
 xcsoar-docker-env:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - id: string 
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./ide
          file: ./ide/docker/Dockerfile
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/xcsoar-build:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
