on:
  workflow_dispatch:  
  push:
    paths-ignore:
      - 'doc/**'
      - 'ide/**'
      - '.github/workflows/build-container.yml'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'ide/**'
      - '.github/workflows/build-container.yml'
    branches:
      - master
env:
  TARGET: ANDROID
jobs:
  xcsoar-compile-android:
    runs-on: ubuntu-latest
    steps:
     - id: checkout 
       uses: actions/checkout@v2
       with:
         submodules: True
     - id: cache-ccache
       uses: hendrikmuhs/ccache-action@v1
       with:
         key: ${{ matrix.os }}-${{ matrix.type }}-${{ env.TARGET }}
     - id: repository
       uses: ASzc/change-string-case-action@v1
       with:
         string: ${{ github.repository }}
     - name: Compile XCSoar
       uses: addnab/docker-run-action@v3
       with:
         image: ghcr.io/${{ steps.repository.outputs.lowercase }}/xcsoar-build:latest
         options: -v ${{ github.workspace }}:/opt/xcsoar -v /home/runner/work/XCSoar/XCSoar/.ccache:/root/.ccache
         run: | 
           cd /opt/xcsoar
           xcsoar-compile ${{ env.TARGET }} USE_CCACHE=y V=2 everything
