/* Generated by Together */

#include "LineStartPoint.hpp"

double LineStartPoint::score_adjustment() {
  return 0.0;
}

GEOPOINT LineStartPoint::get_boundary_parametric(double t) 
{ 
  return oz.get_boundary_parametric(t);
}
